import { computeProration } from "@/lib/billing/proration";
import { computeLine } from "@/lib/billing/line";
import { resolveUnitPrice, type PriceRuleLike } from "@/lib/billing/pricing";
import type { SeatAddition } from "@/lib/billing/changelog";
import type { ExceptionType } from "@prisma/client";

/**
 * Billing-run line generation.
 *
 * Given a billing period and a client's TD SYNNEX subscriptions, this produces
 * the proposed invoice lines plus a list of exceptions for anything that can't
 * be billed cleanly (unmapped SKU, unresolved price). It is pure so the preview
 * and the persisted run are generated by identical logic — what you review is
 * exactly what gets saved.
 */
export interface GenerationPeriod {
  start: Date;
  end: Date;
}

export interface SubscriptionInput {
  id: string;
  sku: string | null;
  productName: string | null;
  quantity: number;
  unitCost: number | null;
  /** Vendor-suggested customer price; used as the unit price when no rule applies. */
  customerPrice?: number | null;
  currency: string | null;
  /** Subscription activation within/around the period (for proration). */
  activeStart?: Date | null;
  activeEnd?: Date | null;
  /**
   * Seats added mid-period (from the Stellr change log). When present, these
   * seats are split off the base quantity onto their own pro-rated line(s), and
   * the base line bills only the seats that were active for the whole period.
   */
  monthlyAdditions?: SeatAddition[];
}

export interface ProductMappingInput {
  /** SKU -> resolved QBO item. Absent entry => unmapped. */
  [sku: string]: { qboItemId: string | null; qboItemName: string | null };
}

export interface GeneratedLine {
  tdSynnexSubscriptionId: string;
  qboItemId: string | null;
  description: string;
  quantity: number;
  unitPrice: number;
  prorationFactor: number;
  proratedDays: number;
  periodDays: number;
  discount: number;
  adjustment: number;
  estimatedCost: number | null;
  subtotal: number;
  total: number;
  /** True for a pro-rated line covering seats added mid-period. */
  isProratedAddition?: boolean;
}

export interface GenerationException {
  type: ExceptionType;
  message: string;
  sku?: string | null;
  subscriptionId?: string;
}

export interface GenerationResult {
  lines: GeneratedLine[];
  exceptions: GenerationException[];
}

export interface GenerateInput {
  clientId: string;
  period: GenerationPeriod;
  subscriptions: SubscriptionInput[];
  mappings: ProductMappingInput;
  priceRules: PriceRuleLike[];
}

export function generateBillingLines(input: GenerateInput): GenerationResult {
  const lines: GeneratedLine[] = [];
  const exceptions: GenerationException[] = [];

  for (const sub of input.subscriptions) {
    if (!sub.sku) {
      exceptions.push({
        type: "UNMAPPED_SKU",
        message: `Subscription ${sub.id} has no SKU and cannot be billed.`,
        subscriptionId: sub.id,
      });
      continue;
    }

    // Resolve the QBO item mapping. An unmapped SKU is still included as a line
    // so the run shows the full invoice — it's flagged (qboItemId null → renders
    // "No QBO item"), recorded as a reconciliation exception, and skipped at push
    // (which sends the run to PARTIALLY_FAILED). Only a subscription with no price
    // at all is dropped, since we can't put a number on the line.
    const mapping = input.mappings[sub.sku];
    const qboItemId = mapping?.qboItemId ?? null;
    const qboItemName = mapping?.qboItemName ?? null;
    if (!qboItemId) {
      exceptions.push({
        type: "UNMAPPED_SKU",
        message: `SKU ${sub.sku} is not mapped to a QuickBooks item.`,
        sku: sub.sku,
        subscriptionId: sub.id,
      });
    }

    const price = resolveUnitPrice({
      rules: input.priceRules,
      clientId: input.clientId,
      sku: sub.sku,
      baseCost: sub.unitCost,
    });
    // Use the resolved rule price; otherwise fall back to the vendor-suggested
    // customer price so a run produces real numbers before any rules exist.
    let unitPrice = price.unitPrice;
    if (unitPrice == null && sub.customerPrice != null) {
      unitPrice = sub.customerPrice;
    }
    if (unitPrice == null) {
      exceptions.push({
        type: "MISSING_PRICE",
        message: `No price rule or vendor price for SKU ${sub.sku}.`,
        sku: sub.sku,
        subscriptionId: sub.id,
      });
      continue;
    }

    const baseDescription = sub.productName ?? qboItemName ?? `SKU ${sub.sku}`;

    // Seats added within this period bill on their own pro-rated line(s); the
    // base line then covers only the seats active for the whole period.
    const additions = (sub.monthlyAdditions ?? []).filter((a) => {
      const t = a.date.getTime();
      return (
        a.seats > 0 &&
        t >= input.period.start.getTime() &&
        t < input.period.end.getTime()
      );
    });
    const addedSeats = additions.reduce((acc, a) => acc + a.seats, 0);
    // Never drive the base line negative if the data disagrees; clamp at 0.
    const baseQuantity = Math.max(0, sub.quantity - addedSeats);

    const proration = computeProration({
      periodStart: input.period.start,
      periodEnd: input.period.end,
      activeStart: sub.activeStart,
      activeEnd: sub.activeEnd,
    });

    if (baseQuantity > 0) {
      const { subtotal, total } = computeLine({
        quantity: baseQuantity,
        unitPrice,
        prorationFactor: proration.factor,
      });
      lines.push({
        tdSynnexSubscriptionId: sub.id,
        qboItemId,
        description: baseDescription,
        quantity: baseQuantity,
        unitPrice,
        prorationFactor: proration.factor,
        proratedDays: proration.billedDays,
        periodDays: proration.periodDays,
        discount: 0,
        adjustment: 0,
        estimatedCost:
          sub.unitCost != null
            ? round2(sub.unitCost * baseQuantity * proration.factor)
            : null,
        subtotal,
        total,
      });
    }

    // One pro-rated line per mid-period seat addition, billed from the day the
    // seats were added through period end.
    for (const add of additions) {
      const activeStart = new Date(
        Date.UTC(
          add.date.getUTCFullYear(),
          add.date.getUTCMonth(),
          add.date.getUTCDate(),
        ),
      );
      const addProration = computeProration({
        periodStart: input.period.start,
        periodEnd: input.period.end,
        activeStart,
        activeEnd: sub.activeEnd,
      });
      const { subtotal, total } = computeLine({
        quantity: add.seats,
        unitPrice,
        prorationFactor: addProration.factor,
      });
      const addedLabel = activeStart.toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        timeZone: "UTC",
      });
      lines.push({
        tdSynnexSubscriptionId: sub.id,
        qboItemId,
        description: `${baseDescription} — added ${addedLabel} (pro-rated ${addProration.billedDays}/${addProration.periodDays} days)`,
        quantity: add.seats,
        unitPrice,
        prorationFactor: addProration.factor,
        proratedDays: addProration.billedDays,
        periodDays: addProration.periodDays,
        discount: 0,
        adjustment: 0,
        estimatedCost:
          sub.unitCost != null
            ? round2(sub.unitCost * add.seats * addProration.factor)
            : null,
        subtotal,
        total,
        isProratedAddition: true,
      });
    }
  }

  return { lines, exceptions };
}

/** Sum the totals of generated lines (run grand total). */
export function sumLineTotals(lines: GeneratedLine[]): number {
  return round2(lines.reduce((acc, l) => acc + l.total, 0));
}

function round2(n: number): number {
  return Math.round((n + Number.EPSILON) * 100) / 100;
}
